name: uchat365
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  smooth_page_indicator: ^1.0.0+2
  #Form Validator
  form_field_validator: ^1.1.0
  #Fire Base
  firebase_core: ^1.17.1
  firebase_auth: ^3.3.7
  cloud_firestore: ^3.1.8
  #Google Fonts
  google_fonts: ^3.0.1
  #For Shared Preferences
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.15
  #Flutter toasts
  fluttertoast: ^8.0.9
  #Flutter vibrate
  flutter_vibrate: ^1.3.0
  flutter_slider_drawer: ^2.1.1
  flutter_chat_bubble: ^2.0.0

#  firebase_messaging: ^12.0.0
  firebase_messaging:
#  ^7.0.3

  flutter_local_notifications: ^5.0.0+4

  internet_connection_checker: ^0.0.1+1
  overlay_support: ^1.2.1
  connectivity_plus: ^1.0.4

  custom_pop_up_menu: ^1.0.0

  emoji_picker_flutter: ^1.3.1

  date_format: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  flutter_native_splash: ^2.0.1+1

flutter_native_splash:
  color: "#ffffff"
  image: assets/splash.png

flutter:

  uses-material-design: true

  assets:
    - logo/
    - assets/
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
